extend network data to support blockbook
bitaccess/coinlib pull request #278
Opened 2022-03-06 02:08 UTC by lexy212

# Description of the change

(Description here)

2022-03-16 13:40 UTC, dzdidi reviewed
General suggestions nothing blocking

2022-03-16 13:40 UTC, dzdidi commented on packages/coinlib-ethereum/src/EthereumPaymentsUtils.ts
> +    tx.to = tx.to ? tx.to.toLowerCase() : ''
For you interest, you can use https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining like this:
```
tx.from = tx.from?.toLowerCase() || ''
tx.to = tx.to?.to.toLowerCase() || ''
```

2022-03-16 13:40 UTC, dzdidi commented on packages/coinlib-ethereum/src/EthereumPaymentsUtils.ts
> +      raw: raw,
You can use ES6 notation here by:
```
{
  ...
  time: new Date(isNumber(raw.timestamp) ? raw.timestamp * 1000 : raw.timestamp),
  raw,
}

2022-03-16 13:40 UTC, dzdidi commented on packages/coinlib-ethereum/src/utils.ts
> +} {
It would be safer to order conditionals bellow from more complex to more primitive types, do  `if/else if/else`, and `server` property of returned value does not seem to be used anywhere. 

If I understand correctly, the `EthereumBlockbookConnectedConfig` type is created specifically for this function. This makes it unclear why use `Pick` especially when the only invocation of this function is explicit in not providing any other parameters from this type rather then picked ones

2022-03-17 13:08 UTC, lexy212 commented on packages/coinlib-ethereum/src/EthereumPaymentsUtils.ts
> +    tx.to = tx.to ? tx.to.toLowerCase() : ''
all these changes were made the auto-formatter prettier.

 It's from the old code. I'll update the PR.

2022-03-17 13:08 UTC, lexy212 commented on packages/coinlib-ethereum/src/EthereumPaymentsUtils.ts
> +      raw: raw,
same as above

2022-04-06 12:14 UTC, lexy212 commented
@dylanseago @dzdidi pls review. I've also updated the PR description for more details.

2022-04-06 17:06 UTC, dzdidi commented on packages/coinlib-ethereum/src/NetworkData.ts
> +    return blockBookAddressDetails
why not ?
```
return this.blockBookService.getAddressDetails(address, options)
```

2022-04-06 17:37 UTC, dzdidi commented on packages/coinlib-ethereum/test/NetworkData.test.ts
> +    blockBookConfig: { nodes: BLOCKBOOK_NODES },
why is 
```
    web3Config: {
      web3,
    },
```
but 
```
blockBookConfig: { nodes: BLOCKBOOK_NODES },
```
?

2022-04-06 20:21 UTC, lexy212 commented on packages/coinlib-ethereum/src/EthereumBlockBook.ts
> +    return this._handleException(async () => {
@dzdidi 
The idea of the helper is to catch exceptions in the code. if there's an exception when the function executes, it should log  the exception, along the function name e.g `EthereumBlockbook.getBlock`(this makes tracing easy) and return null. 

That way we can know there was a problem in the function.  It doesn't necessarily have to be `null`, it could be something like this. 
```ts
{
       ok: boolean,
       error: string
}
```
the `null` here is just a way of saying that there was a problem in this function execution. Then we can check in the caller and then use the other data source.

2022-04-06 20:25 UTC, lexy212 commented on packages/coinlib-ethereum/test/NetworkData.test.ts
> +    blockBookConfig: { nodes: BLOCKBOOK_NODES },
I can either instantiate here or allow the NetworkData class to instantiate it via the blockbook service. 

It works either ways. If I passed an already instantiated blockbook api, it would use that. and if doesn't exist it would create an api instance from the nodes url

@dzdidi

2022-04-06 21:27 UTC, dzdidi commented on packages/coinlib-ethereum/test/NetworkData.test.ts
> +    blockBookConfig: { nodes: BLOCKBOOK_NODES },
sorry, my question was about single line and multiline notations here

2022-04-06 21:27 UTC, dzdidi commented on packages/coinlib-ethereum/src/EthereumBlockBook.ts
> +    return this._handleException(async () => {
> if there's an exception when the function executes, it should log the exception, along the function name e.g EthereumBlockbook.getBlock(this makes tracing easy)

To make tracing easier log `error.stack` instead of `error.toString()` 

> That way we can know there was a problem in the function. It doesn't necessarily have to be null, it could be something like this.
{
       ok: boolean,
       error: string
}
the null here is just a way of saying that there was a problem in this function execution. Then we can check in the caller and then use the other data source.

And this object is already quite close to the error object by structure still being less descriptive due to missing call stack, and having boolean status. At the same time being inferior in behaviour as 
a) runtime errors are autogenerated (instead of passing function name as parameter)
b) they interrupt flow by default (instead of doing `if(!x) return null`

2022-04-08 14:19 UTC, dzdidi approved these changes

2022-04-21 20:15 UTC, dylanseago requested changes

2022-04-21 20:15 UTC, dylanseago commented on packages/coinlib-ethereum/src/NetworkData.ts
>    async getNetworkData(
Do you mind renaming this while you're changing things here anyway? It doesn't accurately describe what it's purpose is. Perhaps `getGasAndNonceForNewTx` would be more descriptive.

2022-04-21 20:15 UTC, dylanseago commented on packages/coinlib-ethereum/src/UnitConvertersUtil.ts
> +export abstract class UnitConvertersUtil {
Nice addition. I like that you added this class. However I don't think this needs to be `abstract` because it has no unimplemented `abstract` methods.

2022-04-21 20:15 UTC, dylanseago commented on packages/coinlib-ethereum/src/EthereumBlockBook.ts
> +export class EthereumBlockbook extends UnitConvertersUtil {
This name is easy to get mixed up with `BlockbookEthereum`, so I think it'd be a good idea to pick something more distinct. What do you think about these renamings?
- `EthereumBlockBook` -> `NetworkDataBlockbook`
- `EthereumWeb3` -> `NetworkDataWeb3`

Also, are you able to create a common, shared interface between these two data providers? If so that would be a great improvement in clarity

2022-04-28 00:34 UTC, lexy212 commented on packages/coinlib-ethereum/src/NetworkDataBlockbook.ts
> +  async getTransactionInfoERC20(txId: string, tokenAddress?: string) {
@dylanseago this is the most significant change in the newly pushed updates.

2022-04-28 00:38 UTC, lexy212 commented on packages/coinlib-ethereum/src/NetworkDataBlockbook.ts
> +      // so we have to use a custom unitConverter, the default one uses that 18 decimals
blockbook is kind enough to tell us the decimal places for the tokens. otherwise we might use our default 18dp therefore the amount would be wrong.

2022-05-02 17:22 UTC, lexy212 commented on packages/coinlib-ethereum/src/NetworkDataStandardizationUtils.ts
> +export class NetworkDataStandardizationUtils {
The idea of this helper is to map the data from either providers to a standard interface.

2022-05-02 17:23 UTC, lexy212 commented on packages/coinlib-ethereum/src/types.ts
> +}
both providers implements all the methods defined here.

2022-05-02 17:25 UTC, lexy212 commented
@dylanseago this is ready again for review

2022-05-03 19:05 UTC, dylanseago requested changes

2022-05-03 19:07 UTC, dylanseago commented on packages/coinlib-ethereum/src/types.ts
> +}
These divergent signatures for both methods are what you should aim to unify into a single shared API

2022-05-04 10:20 UTC, lexy212 commented on packages/coinlib-ethereum/src/NetworkDataStandardizationUtils.ts
> +export class NetworkDataStandardizationUtils {
Oh sounds good. I initially wanted to reduce the responsibility of the Network Data providers to a simple `get`. nothing more, but it seems it makes more sense to standardize in the same context.

2022-05-04 18:05 UTC, dylanseago requested changes

2022-05-04 18:05 UTC, dylanseago commented on packages/coinlib-ethereum/src/EthereumPaymentsUtils.ts
> -    }
Users of this library depend on this logic because they only use the `getTransactionInfo` method. The `getTransactionInfoERC20` should actually be considered a private helper method that isn't exposed as part of the top level library interface. It's designed this way is so that there's a single public API for retrieving transaction info, whether it's a token or not.

2022-05-06 14:07 UTC, dylanseago approved these changes

2022-05-12 23:48 UTC, merged