Fix breaking tests
bitaccess/coinlib pull request #295
Opened 2022-05-18 16:10 UTC by lexy212

# Description of the change

(Description here)

2022-05-18 18:08 UTC, dylanseago requested changes

2022-05-18 18:08 UTC, dylanseago commented on packages/coinlib-ethereum/test/HdEthereumPayments.test.ts
> +process.env.NODE_DEBUG = 'ethereum-payments'
Please remove before merging

2022-05-18 18:08 UTC, dylanseago commented on packages/coinlib-ethereum/test/HdEthereumPayments.test.ts
> -      test.skip('returns transaction by id (included into block and failed)', async () => {
Why were these tests removed?

2022-05-18 18:16 UTC, lexy212 commented on packages/coinlib-ethereum/test/HdEthereumPayments.test.ts
> +process.env.NODE_DEBUG = 'ethereum-payments'
it's still WIP. Thanks for the reminder.

2022-05-18 18:16 UTC, lexy212 commented on packages/coinlib-ethereum/test/HdEthereumPayments.test.ts
> -      test.skip('returns transaction by id (included into block and failed)', async () => {
I redid this tests, if we look how how `getTransactionInfo` is works, it's impossible to have a `failed` transaction.

At best we can only have a transaction with status = `pending` or `confirmed`.

2022-05-18 20:07 UTC, dylanseago commented on packages/coinlib-ethereum/test/HdEthereumPayments.test.ts
> -      test.skip('returns transaction by id (included into block and failed)', async () => {
But it's not impossible to have a failed transaction on Ethereums network. So we need a way to accommodate such situations. For example, here's a failed transaction that ran out of gas, so nothing was transferred.
https://ropsten.etherscan.io/tx/0xabacaa58c1287b29ae9fa819693c3ebb412d5e46dcb302ee914b191818106713

2022-05-19 17:48 UTC, lexy212 commented
All tests are now passing.

2022-05-19 20:40 UTC, dylanseago approved these changes

2022-05-19 23:33 UTC, merged