Feat/fingerprint
bitaccess/coinlib pull request #315
Opened 2022-07-14 15:23 UTC by caleb-bitaccess

# Description of the change

add deriveUniPubKeyForPath and deriveUniPubKeyForPath to all coin's paymentsUtils

2022-07-14 17:57 UTC, dylanseago requested changes

2022-07-14 17:57 UTC, dylanseago commented on packages/coinlib-bitcoin-cash/src/helpers.ts
> +    throw new TypeError(`Purpose in derivationPath ${purpose} not supported by Bitcoincash`)
No need to enforce this. You can use any custom derivation path you like with any address type you like. The purposes are just a convention. There could very likely be a customer that wants to use `45'` or `48'` as they're common multisig paths, or something else entirely custom.

2022-07-14 17:57 UTC, dylanseago commented on packages/coinlib-bitcoin-cash/src/helpers.ts
> +    throw new TypeError(`Invalid derivationPath coin type ${coinType}`)
In order to avoid this whole if/else structure you could just require `networkType` as a parameter. This would reduce the edge cases and be totally reasonable because the utils calling this helper already have `networkType` as an instance variable.

2022-07-14 17:57 UTC, dylanseago commented on packages/coinlib-bitcoin-cash/test/BitcoinCashPaymentsUtils.test.ts
> +  })
Great tests!

2022-07-14 17:57 UTC, dylanseago commented on packages/coinlib-bitcoin/src/bitcoinish/constants.ts
> +export const NETWORK_TESTNET = networks.testnet
I believe these 4 constants above would be more appropriate in `src/constants.ts` since they're bitcoin specific and not generally applicable to all bitcoinish coins

2022-07-14 17:57 UTC, dylanseago commented on packages/coinlib-bitcoin/src/helpers.ts
> +  return account.neutered().toBase58()
Could both of these helpers be generalized and moved into bitcoinish or common instead? I see a lot of repetitive logic that could be deduplicated.

Something like:
```
function createDeterminePathForIndexHelper(constants: {
  addressTypePurposes: { [addressType: string]: string },
  coinTypes: { [networkType in NetworkType]: string },
}) {
  return (
    accountIndex: number,
    addressType?: BitcoinishAddressType,
    networkType?: NetworkType,
  ): string => {
    // implementation goes here and uses `constants` param provided through closure 
  }
}
```

A similar pattern can be adopted for `deriveUniPubKeyForPath`

2022-07-14 17:57 UTC, dylanseago commented on packages/coinlib-common/src/PaymentsUtils.ts
> +    addressType?: BitcoinishAddressType,
Moving this `BitcoinishAddressType` into common isn't really appropriate since it's only applicable to bitcoinish coins, not all networks generally. I'd recommend following the pattern of the other methods above that also have optional parameters that may or may not be used in different ways by different networks.

For example:
```
isValidAddress<O extends { format?: string }>(address: string, options?: O): boolean
```
The `format` field here is an enum for ethereum style networks, but unused by other networks. You could do something similar for addressType so that it's general enough to be used for both bitcoinish address types, and any other potential variability in other networks addresses.

```
determinePathForIndex<O extends { addressType?: string }>(accountIndex: number, options?: O): string
```

Then inside your bitcoinish implementations you'd just use:
```
const addressType = options?.addressType ? assertType(AddressTypeT, options?.addressType) : DEFAULT_ADDRESS_TYPE
```

2022-07-18 20:19 UTC, dylanseago commented
@caleb-bitaccess Have all the previous review comments been addressed? If so please mark them as resolved

2022-07-18 20:42 UTC, caleb-bitaccess commented on packages/coinlib-bitcoin-cash/src/helpers.ts
> +    throw new TypeError(`Purpose in derivationPath ${purpose} not supported by Bitcoincash`)
restriction removed

2022-07-18 20:50 UTC, caleb-bitaccess commented on packages/coinlib-bitcoin/src/bitcoinish/constants.ts
> +export const NETWORK_TESTNET = networks.testnet
removed

2022-07-18 20:50 UTC, caleb-bitaccess commented on packages/coinlib-bitcoin/src/helpers.ts
> +  return account.neutered().toBase58()
put them in bitcoinish helper

2022-07-18 20:50 UTC, caleb-bitaccess commented on packages/coinlib-common/src/PaymentsUtils.ts
> +    addressType?: BitcoinishAddressType,
removed BitcoinishAddressType from coinlib-common

2022-07-18 20:50 UTC, caleb-bitaccess commented on packages/coinlib-tron/src/helpers.ts
> +  }
checking removed

2022-07-18 20:50 UTC, caleb-bitaccess commented on packages/coinlib/src/utils.ts
> +}
added getFingerprint() to  CoinPayments, but I kept these two methods here.

2022-07-18 20:50 UTC, caleb-bitaccess commented on packages/coinlib-ethereum/src/helpers.ts
> +  if (addressType && addressType?.toString() !== LEGENCY) {
removed

2022-07-25 15:15 UTC, dylanseago approved these changes

2022-07-25 15:58 UTC, merged