Feat/seed
bitaccess/coinlib pull request #324
Opened 2022-08-05 00:45 UTC by caleb-bitaccess

#  Add seed and derivationPath to all UHdConfig

To allow all coins have a unified config interface

- add UHd*Payments classes
- add UHd*PaymentsConfig
- add tests

2022-08-05 16:22 UTC, dylanseago requested changes
I would recommend moving duplicate tests into helpers within each test folder. Having to maintain all these additional ones will make future changes more tedious

2022-08-05 17:57 UTC, caleb-bitaccess commented on packages/coinlib-bitcoin-cash/src/UHdBitcoinCashPayments.ts
> +      const rootNode = determineHdNode(seed)
`derivationPath` is passed in config to parent Hd class.  Need to change the rest coins to support a customized derivation path in future sprints.

2022-08-05 18:06 UTC, caleb-bitaccess commented on packages/coinlib-ripple/src/types.ts
> +  [HdRipplePaymentsConfig, UHdRipplePaymentsConfig, AccountRipplePaymentsConfig],
Nope. This trick does not help. TS still thinks the type is too complex.

2022-08-08 15:42 UTC, dylanseago commented on packages/coinlib-litecoin/test/UHdLitecoinPayments.test.ts
> +// function runHardcodedPublicKeyTests(
What's with these comments?

2022-08-08 18:17 UTC, dylanseago approved these changes

2022-08-08 18:17 UTC, merged